apiVersion: v1
kind: ConfigMap
metadata:
  name: imagik-config
data:
  IMAGIK_ROOT: /data/images
  # Sentry configuration
  SENTRY_ENVIRONMENT: beryjuorg-prod
  # Run `docker run -it --rm beryju/imagik generate-key` to get a secret key for session
  # IMAGIK_SECRET: "output"

  # Run `docker run -it --rm beryju/imagik hash-password` to get a password hash
  # if you want to use the webinterface
  # IMAGIK_AUTH_DRIVER: "static"
  # IMAGIK_USER: "username"
  # IMAGIK_PASSWORD: "output"
